ISLANDORA-2218: Add parent column for inactive object management table
Islandora/islandora_simple_workflow pull request #43
Opened 2018-05-07 14:50 UTC by BrandonMorr

**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-2218

# What does this Pull Request do?

Add a new configuration option to toggle a 'Parents' column for the Inactive object management list. This new addition should provide helpful links to the parent object(s) for each inactive object.

# What's new?

* Added admin configuration form file admin.inc
* Added islandora_simple_workflow.install to remove configuration variable on module uninstall
* Added menu path 'admin/islandora/tools/simple_workflow/settings', included configuration path in islandora_simple_workflow.info

# How should this be tested?

* Ingest a few different Objects using a variety of cModels (book, large image, pdf, etc.)
* Ensure that each Object's status is set to 'inactive' (may want disable the 'bypass inactive object state' permission to avoid this step)
* In the simple workflow module's settings page enable the parent column.
* Ensure that each inactive object has their parent column information showing up properly (this should include Objects with multiple parents).

Now pick a handful of Objects and set Object viewing XACML restrictions on their parent Object(s) for your test user:
* Refresh the inactive object list and ensure that the parent Objects that you no longer have access to don't show up under the column.

# Interested parties
I can't seem to ping the committers group, so I'll just ping @jordandukart :-)

2018-05-07 17:49 UTC, bondjimbond commented
@BrandonMorr Thanks for this improvement. It's certainly helpful. 

Test results are good. Travis died on the first attempt, so I'll wait till its results come back.

@Islandora/7-x-1-x-committers Any comments on this additional setting?

2018-05-08 13:56 UTC, rosiel approved these changes
Awesome. (and works).

2018-05-08 14:00 UTC, qadan approved these changes
Been through the wringer here internally at DGI, gets my thumbs up 👍

2018-05-08 14:03 UTC, DiegoPino requested changes
Folks. Do we need another toggle in our lives?

2018-05-08 14:03 UTC, DiegoPino commented on includes/admin.inc
> +function islandora_simple_workflow_admin_form(array $form, array &$form_state) {
Wonder if we reeaaaaaally need another toggle. Can this be just shown by default??

2018-05-08 14:03 UTC, DiegoPino commented on includes/manage.inc
> +    $render_parents = variable_get('islandora_simple_workflow_toggle_parent_column', FALSE);
Is there a need for not showing the new parent column? This is a great improvement but a toggle means documentation

2018-05-08 14:05 UTC, DiegoPino commented
Ups. Sorry. I wanted to jsut comment, not block. But anyway. If I approve now I will forget the conversation I want to start 🧀 .  Why/How showing the new awesome parent column always will make users angry and demand for a toggle? Islandora IS FULL of toggles. Do we need another one for an option that hurts nobody? Toggle == new screenshot == documentation == support.

2018-05-08 14:08 UTC, willtp87 commented
@DiegoPino This feature will be prohibitively expensive for some situations. As I understand it the form does not page. Paging would be a separate issue that should not be handled here.

2018-05-08 14:19 UTC, bondjimbond commented
> This feature will be prohibitively expensive for some situations. As I understand it the form does not page. Paging would be a separate issue that should not be handled here.

At first I agreed with @DiegoPino that a toggle isn't necessary, but @willtp87 makes an interesting point.

How often does such a circumstance come up? I would be surprised to see a repository with so many inactive objects that listing their parents alongside them would eat up an intolerable amount of resources.

2018-05-08 14:32 UTC, DiegoPino commented
@BrandonMorr @bondjimbond @rosiel , @willtp87 is right, I understand the tech/performance concern since there is no paging here. I just realized that...
```foreach ($inactive_objects as $inactive_object) ```` hu! , performance will be a concern even withpout the parents if we have a LOT of inactive objects. I remember the issue with making post variables very large in find and replace module because of the same issue, no paging.

So, what do you think? another toggle or add paging?

2018-05-08 14:38 UTC, bondjimbond commented
@DiegoPino If the user can configure the number of items in a page, I'd be happy with that -- personally I prefer working with a complete list unless I'm getting a performance hit, so I'd like the option to list all objects.

2018-05-08 14:46 UTC, DiegoPino commented
a list of 10000? You are Brave! I will not vote for another toggle/admin option, but I will agree with anything you all agree on. Removing for now the changes request. But I think having a toggle to avoid performance issues is not a good idea, specially if the issues can be avoided completely.

2018-05-08 15:34 UTC, bondjimbond commented
> a list of 10000? You are Brave!

@DiegoPino  If it gets that high, I'd enable paging. :)

I think paging is best so long as user can choose how many fit on a page (50, 100, 1000, all?)

2018-05-08 16:22 UTC, rosiel commented
This ticket is for a very small improvement, with a nod to potential performance issues, and I think it's fine as it is. I hate toggles too, but i don't think we should block this until 5x the work can be done!  

The "foreach" part is probably fine - even for 10,000 objects - it just populates the table (not saying your browser is gonna be happy, but within that loop there's no object loading unless $render_parents is on). 

Still, I see you, and agree it should be paged, but that deserves a separate ticket.

We could probably get parent info in the sparql query if we're considering performance. And if we go that way, we could include the object owner and the created date and other useful things in the RI...  
so there are a lot of things i'd redesign here if i had my way but this little improvement is good. 

Um yes. It does need to be documented and a new screenshot made though.

2018-05-09 16:41 UTC, willtp87 commented
@DiegoPino  in https://github.com/Islandora/islandora_simple_workflow/pull/43#issuecomment-387427960 you comment that you are removing the requested changes but you are flagged as requesting changes.  Is this intentional?

2018-05-09 16:45 UTC, BrandonMorr commented
@rosiel - Just for clarification, is the documentation blocking this pull request from being merged?

2018-05-09 16:53 UTC, DiegoPino approved these changes

2018-05-09 17:06 UTC, DiegoPino commented
@willtp87 confusing from my part. I don't feel an extra toggle here is a good an idea and approving will give the impression I'm ok with merging. So, that. I release the lock, but I'm not an advocate of tiny improvements leaving other issues around.

2018-05-10 17:53 UTC, rosiel commented
not a blocker; i'll file a ticket immediately, but PLEASE folks let's start documenting our new features! #documentationAsAFirstClassCitizen

2018-05-16 14:18 UTC, DiegoPino commented
@rosiel @bondjimbond  if you are OK with this feel free to move forward. Is the paging/documenting Jira ticket already made? thanks

2018-05-16 15:04 UTC, merged

2018-05-16 15:17 UTC, rosiel commented
Documentation ticket: https://jira.duraspace.org/browse/ISLANDORA-2228
Paging ticket: https://jira.duraspace.org/browse/ISLANDORA-2230

2018-05-16 15:20 UTC, DiegoPino commented
Thanks @rosiel!!

2018-05-16 15:26 UTC, nhart commented
Thank you!

2018-05-16 16:03 UTC, BrandonMorr commented
Thanks a lot guys!!